travis:
  secure:
    BINSTAR_TOKEN: RlUNooxkhk/EUY+zPWp6xrlSvS+2pQGnUKpbDrqYWvw/O0zxV9Jp7kLv/w990hwXAQsr5lN7oEED5kLEyODjSPnAuH2Qwx+mS2knGtOxtmu1CQx1F342+nfhLkYBxoRu0t0bY9THRieE1vxE30znZp1ii8w4ihCr2fl7y7YY1MWk97DEbbaXLigAZQiiOc0kfY6a805tptyciZjeHf2MCYPY7q12adlg1NvwHWK9OR67GOFXg78deoVmhiJPGqcynd5ViIDXrthvIY635++blxJLtKYZWKXLK6ZF2mzLaoaUGITpzmjQ88VDTkYc1ktnm/LyOcolgpffH8qGGBxvi6uxx/2ASar0jN2dbdoDk/OQoaZ6vb6po+jdxgLr/+qheyrlK0qK9PJGmw/BeBtEGVV+/+eDzjr5L9VTfyPcJwBQXZW6L5pplHLPlFpbhZSYucmtG1m66bVthCjXbLukxs9U+/KDgDmiahuh29Kgfb4+szLYjW58B/b978lwdSqMm90kTOJjXQPNkQkLXK/SHHT9VP/mqwICIjoBrLQ7gVG5NaqCOgBEV6vU1VAsATo6743AbSaMnzSHH6k8N+0pQKVee8UOS8fJTqbR1877+rm/6TUN9QqWr0TGojxhS61/MlbrWqxMmrF7OGllcYbfrHUm9Y/pisTc/NlJa0bD3cc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
